version: '3.8'

services:
  vehicle-detection:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MPLCONFIGDIR=/tmp/matplotlib
      - YOLO_CONFIG_DIR=/tmp/ultralytics
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/tmp/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s